//Estado productos
export const OBTENER_PRODUCTOS_EXITO = 'OBTENER_PRODUCTOS_EXITO'

//Estado Pedido
export const SELECCIONAR_PRODUCTOS = 'SELECCIONAR_PRODUCTO'
export const GUARDAR_PEDIDO = 'GUARDAR_PEDIDO'
export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN'
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO'